language: node_js
node_js:
  - 13

script:
  - npm run-script reindex

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file: 
    - "reindex_dist/database.json"
    - "reindex_dist/database.min.json"
    skip_cleanup: true
    on:
      tags: true